server:
    port: 8081
    contextPath: /neurologia
    
loggin:
    level:
       org.hibernate.SQL: DEBUG       
       org.hibernate.type: TRACE
       
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/medraapimsdb?useUnicode=true&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=America/Argentina/Buenos_Aires
        username: root
        password: root
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
      show-sql: true
      #none, update, create, create-drop
      hibernate.ddl-auto: none      
      hibernate:
          format_sql: true
          use_sql_comments: true                   
          #ddl-auto: create
          naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
          dialect: org.hibernate.dialect.MySQL5Dialect